In [1]:
import pandas as pd
import numpy as np

In [2]:
iris_df = pd.read_excel('iris.xls')

In [3]:
iris_df.head()

SL   SW   PL   PW Classification
0  5.1  3.5  1.4  0.2    Iris-setosa
1  4.9  3.0  1.4  0.2    Iris-setosa
2  4.7  3.2  1.3  0.2    Iris-setosa
3  4.6  3.1  1.5  0.2    Iris-setosa
4  5.0  3.6  1.4  0.2    Iris-setosa

In [4]:
iris_df.shape

(150, 5)

In [5]:
iris_df.isna().sum()

SL                0
SW                0
PL                0
PW                0
Classification    0
dtype: int64

In [6]:
X = iris_df.drop('Classification',axis=1)
y= iris_df['Classification']

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

In [8]:
from sklearn.metrics import accuracy_score,confusion_matrix,f1_score

In [9]:
from sklearn.linear_model import LogisticRegression
log_model = LogisticRegression(multi_class='multinomial')
log_model.fit(X_train,y_train)
y_pred = log_model.predict(X_test)
print('Accuracy is :', accuracy_score(y_test,y_pred))
confusion_matrix(y_test,y_pred)

Accuracy is : 1.0


array([[10,  0,  0],
       [ 0,  9,  0],
       [ 0,  0, 11]], dtype=int64)

In [10]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=4,metric='euclidean')
knn.fit(X_train,y_train)
y_pred = knn.predict(X_test)
print('Accuracy for k=4: ',accuracy_score(y_test,y_pred))
confusion_matrix(y_test,y_pred)

Accuracy for k=4:  1.0


array([[10,  0,  0],
       [ 0,  9,  0],
       [ 0,  0, 11]], dtype=int64)

In [11]:
from sklearn.svm import SVC
svm_linear = SVC(kernel='rbf')
svm_linear.fit(X_train,y_train)
y_pred = svm_linear.predict(X_test)
print('Accuracy is :', accuracy_score(y_test,y_pred))
confusion_matrix(y_test,y_pred)

Accuracy is : 1.0


array([[10,  0,  0],
       [ 0,  9,  0],
       [ 0,  0, 11]], dtype=int64)

In [12]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()
rf.fit(X_train,y_train)
y_pred = rf.predict(X_test)

In [13]:
from sklearn.metrics import f1_score
print('f1_score: ',f1_score(y_test,y_pred,average='weighted'))
print('Accuracy  ',accuracy_score(y_test,y_pred))
confusion_matrix(y_test,y_pred)

f1_score:  1.0
Accuracy   1.0


array([[10,  0,  0],
       [ 0,  9,  0],
       [ 0,  0, 11]], dtype=int64)